# Question 1

In [14]:
import numpy as np
np.random.randn(25)

array([-1.98264538, -0.48767619, -0.45749755, -0.09825959, -0.49685859,
       -0.87208343, -0.24228798, -0.71298487,  0.254247  , -0.151952  ,
       -1.10186254,  0.57113756,  1.06144781,  0.20549787,  0.19285262,
       -0.94004378,  1.35758736,  0.99040063, -0.62157919,  3.04195129,
       -0.63487498,  1.05735984,  2.1748317 ,  0.98363525, -0.14914642])

# Question 2

In [5]:
np.random.seed(5)
a = np.random.randint(low=0,high=100,size=(30))
np.mean(a)


50.43333333333333

# Question 3

In [8]:
a = np.arange(1,101).reshape((10,-1))
print(a)
a.shape

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


(10, 10)

# Question 4

In [9]:
np.random.seed(40)
b= np.random.randint(low=0,high=101,size=(10,10))
print("minimum value of the array:{}".format(a.min()))
print("maximum value of array : {}".format(a.max()))

minimum value of the array:1
maximum value of array : 100


# Question 5

In [10]:
i = np.array([1,2,2])
o = np.array([4,5,4])

np.dot(i,o)

22

# Question 6

x=np.array([[1,5],
            [3,5]])
            
y=np.array([[5,6]])

np.concatenate((x,y),axis=0)

# Question 7

In [12]:

a = np.array([1,2,3,2,3,4,3,4,5,6,9,0])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4, 9])

# Question 8

In [13]:

arr = np.array([5,65,6,2,3,85,2,1,233,5])

np.sort(arr)

array([  1,   2,   2,   3,   5,   5,   6,  65,  85, 233])

NameError: name '__dir__' is not defined

In [2]:
directory = os.path.dirname(path)
printz(directory)

NameError: name 'os' is not defined

In [4]:
import os
os.getcwd()

'C:\\Users\\rites'